name: Javadoc Generation

on:
  push:
  pull_request:

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/development-')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Check if Javadoc folder exists
        run: ls -al build/docs/javadoc

      - name: Upload JavaDocs as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc-artifact
          path: build/docs/javadoc/
          if-no-files-found: warn
